version: '3'
networks:
  services:
    ipam:
      config:
        - subnet: 173.17.0.0/24
services:
  webserver:
    image: indy-node
    build:
      context: .
      dockerfile: pool.dockerfile
    command: bash -c './scripts/start_webserver.sh'
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - HOST=173.17.0.100
      - RUST_LOG=${RUST_LOG}
    networks:
      services:
        ipv4_address: 173.17.0.100
    ports:
      - '9000:8000'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    volumes:
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - node1-data:/home/indy/.mnt/node1
      - node2-data:/home/indy/.mnt/node2
      - node3-data:/home/indy/.mnt/node3
      - node4-data:/home/indy/.mnt/node4
  node1:
    image: indy-node
    command: bash -c './scripts/start_node.sh 1'
    networks:
      services:
        ipv4_address: 173.17.0.101
    ports:
      - '9701:9701'
      - '9702:9702'
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node1-data:/home/indy/ledger
  node2:
    image: indy-node
    command: bash -c './scripts/start_node.sh 2'
    networks:
      services:
        ipv4_address: 173.17.0.102
    ports:
      - '9703:9703'
      - '9704:9704'
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node2-data:/home/indy/ledger
  node3:
    image: indy-node
    command: bash -c './scripts/start_node.sh 3'
    networks:
      services:
        ipv4_address: 173.17.0.103
    ports:
      - '9705:9705'
      - '9706:9706'
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node3-data:/home/indy/ledger
  node4:
    image: indy-node
    command: bash -c './scripts/start_node.sh 4'
    networks:
      services:
        ipv4_address: 173.17.0.104
    ports:
      - '9707:9707'
      - '9708:9708'
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node4-data:/home/indy/ledger
  Issuer:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      - >-
        ICON_SRC=https://cdn2.iconfinder.com/data/icons/bubble-education-icons-1/360/School-512.png
      - THEME=OliveDrab
      - PORT=3000
      - NAME=Issuer Agency
      - mailto:email=issuer@issuer.com
      - PASSWORD=123
      - USERNAME=Issuer
      - PUBLIC_DID_ENDPOINT=173.17.0.150:3000
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - '3000:3000'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.150
    volumes:
      - node1-data:/home/indy/ledger
  Verifier:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      - >-
        ICON_SRC=https://cdn2.iconfinder.com/data/icons/bubble-education-icons-1/360/School-512.png
      - THEME=OliveDrab
      - PORT=3001
      - NAME=Verifier Agency
      - mailto:email=verifier@verifier.com
      - PASSWORD=123
      - USERNAME=Verifier
      - PUBLIC_DID_ENDPOINT=173.17.0.151:3001
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - '3001:3001'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.151
    volumes:
      - node1-data:/home/indy/ledger
  mark:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3012'
      NAME: mark
      email: firetortoise1221@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.162:3012
      RUST_LOG: 173.17.0.162
    ports:
      - '3012:3012'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.162
    volumes:
      - node1-data:/home/indy/ledger
  CheckFix:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3034'
      NAME: CheckFix
      email: cfix@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.184:3034
      RUST_LOG: 173.17.0.184
    ports:
      - '3034:3034'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.184
    volumes:
      - node1-data:/home/indy/ledger
  Testuser:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3035'
      NAME: Testuser
      email: test@user.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.185:3035
      RUST_LOG: 173.17.0.185
    ports:
      - '3035:3035'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.185
    volumes:
      - node1-data:/home/indy/ledger
  CarlLewis:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3036'
      NAME: CarlLewis
      email: clewis@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.186:3036
      RUST_LOG: 173.17.0.186
    ports:
      - '3036:3036'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.186
    volumes:
      - node1-data:/home/indy/ledger
  AndyJones:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3037'
      NAME: AndyJones
      email: ajones@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.187:3037
      RUST_LOG: 173.17.0.187
    ports:
      - '3037:3037'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.187
    volumes:
      - node1-data:/home/indy/ledger
  NewUser:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3038'
      NAME: NewUser
      email: nuser@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.188:3038
      RUST_LOG: 173.17.0.188
    ports:
      - '3038:3038'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.188
    volumes:
      - node1-data:/home/indy/ledger
  User:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3039'
      NAME: User
      email: firetortoise@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.189:3039
      RUST_LOG: 173.17.0.189
    ports:
      - '3039:3039'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.189
    volumes:
      - node1-data:/home/indy/ledger
  AdamDan:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3040'
      NAME: AdamDan
      email: adan@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.190:3040
      RUST_LOG: 173.17.0.190
    ports:
      - '3040:3040'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.190
    volumes:
      - node1-data:/home/indy/ledger
  MikeTyson:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3041'
      NAME: MikeTyson
      email: mtyson@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.191:3041
      RUST_LOG: 173.17.0.191
    ports:
      - '3041:3041'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.191
    volumes:
      - node1-data:/home/indy/ledger
  Mehrak:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3042'
      NAME: Mehrak
      email: massadiandc@me.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.192:3042
      RUST_LOG: 173.17.0.192
    ports:
      - '3042:3042'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.192
    volumes:
      - node1-data:/home/indy/ledger
  AndrewFlint:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: bash -c 'sleep 10; npm start'
    environment:
      PORT: '3043'
      NAME: AndrewFlint
      email: aflint@gmail.com
      PASSWORD: 1234
      ICON_SRC: >-
        http://www.clker.com/cliparts/g/l/R/7/h/u/teamstijl-person-icon-blue-hi.png
      THEME: BurlyWood
      PUBLIC_DID_ENDPOINT: 173.17.0.193:3043
      RUST_LOG: 173.17.0.193
    ports:
      - '3043:3043'
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.193
    volumes:
      - node1-data:/home/indy/ledger
volumes:
  webserver-cli: null
  node1-data: null
  node2-data: null
  node3-data: null
  node4-data: null
